
library:
  controller: 'my library controller'

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: 'jdbc:log4jdbc:oracle:thin:@192.168.0.9:1521:XENO'
    username: 'dev_op'
    password: 'xeno0201'
  mybatis:
    type-handlers-package: 'com.xeno.arches.platform.plugins.mybatis.typehandler'
    mapper-locations: 'classpath*:mybatis/mapper/**/*.xml'
    executor-type: simple
    configuration:
      auto-mapping-unknown-column-behavior: warning
      map-underscore-to-camel-case: true
      default-statement-timeout: 60
      jdbc-type-for-null: varchar